# Generated by Django 3.0 on 2020-01-15 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('band', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractGig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('calltime', models.TimeField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Confirmed'), (2, 'Cancelled'), (3, 'Asking')], default=0)),
                ('is_private', models.BooleanField(default=False)),
                ('invite_occasionals', models.BooleanField(default=True)),
                ('was_reminded', models.BooleanField(default=False)),
                ('hide_from_calendar', models.BooleanField(default=False)),
                ('default_to_attending', models.BooleanField(default=False)),
                ('trashed_date', models.DateTimeField(blank=True, null=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to='band.Band')),
            ],
        ),
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('abstractgig_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gig.AbstractGig')),
                ('setlist', models.TextField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('settime', models.TimeField(blank=True, null=True)),
                ('endtime', models.TimeField(blank=True, null=True)),
                ('dress', models.TextField(blank=True, null=True)),
                ('paid', models.TextField(blank=True, null=True)),
                ('postgig', models.TextField(blank=True, null=True)),
                ('rss_description', models.TextField(blank=True, null=True)),
            ],
            bases=('gig.abstractgig',),
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'No Plan'), (1, 'Definitely'), (2, 'Probably'), (3, "Don't Know"), (4, 'Probably Not'), (5, "Can't Do It"), (6, 'Not Interested')], default=0)),
                ('feedback_value', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('snooze_until', models.DateTimeField(blank=True, null=True)),
                ('assoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='band.Assoc', verbose_name='assoc')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='band.Section', verbose_name='section')),
            ],
        ),
    ]
