# Generated by Django 3.0 on 2020-01-05 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='calltime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gig',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='dress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='endtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_gigs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gig',
            name='paid',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='postgig',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='setlist',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='settime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Confirmed'), (2, 'Cancelled'), (3, 'Asking')], default=0),
        ),
    ]
