# Generated by Django 3.0 on 2020-02-29 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gig", "0002_auto_20200225_2110"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalGig",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("details", models.TextField(blank=True, null=True)),
                ("created_date", models.DateTimeField(blank=True, editable=False)),
                ("last_update", models.DateTimeField(blank=True, editable=False)),
                ("date", models.DateTimeField()),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "Confirmed"),
                            (2, "Cancelled"),
                            (3, "Asking"),
                        ],
                        default=0,
                    ),
                ),
                ("is_private", models.BooleanField(default=False)),
                ("invite_occasionals", models.BooleanField(default=True)),
                ("was_reminded", models.BooleanField(default=False)),
                ("hide_from_calendar", models.BooleanField(default=False)),
                ("default_to_attending", models.BooleanField(default=False)),
                ("trashed_date", models.DateTimeField(blank=True, null=True)),
                ("setlist", models.TextField(blank=True, null=True)),
                ("setdate", models.DateTimeField(blank=True, null=True)),
                ("enddate", models.DateTimeField(blank=True, null=True)),
                ("dress", models.TextField(blank=True, null=True)),
                ("paid", models.TextField(blank=True, null=True)),
                ("postgig", models.TextField(blank=True, null=True)),
                ("rss_description", models.TextField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical gig",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
