# Generated by Django 3.0.3 on 2020-02-25 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0002_assoc_member'),
        ('gig', '0002_auto_20200224_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band.Band'),
        ),
    ]
