# Generated by Django 3.0 on 2020-01-19 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0002_assoc_member'),
        ('gig', '0002_auto_20200114_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plansections', to='band.Section', verbose_name='plan_section'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='band.Section', verbose_name='section'),
        ),
    ]
