# Generated by Django 3.0 on 2020-01-22 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0007_auto_20200121_1958'),
        ('gig', '0003_auto_20200118_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plansections', to='band.Section', verbose_name='plan_section'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sections', to='band.Section', verbose_name='section'),
        ),
    ]
