# Generated by Django 3.0 on 2020-01-05 23:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0003_auto_20200105_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
