# Generated by Django 3.0.3 on 2020-03-08 04:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("gig", "0003_historicalgig"),
    ]

    operations = [
        migrations.AddField(
            model_name="gig",
            name="cal_feed_gig",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="historicalgig",
            name="cal_feed_gig",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
