# Generated by Django 3.0.3 on 2020-03-08 13:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("gig", "0004_auto_20200307_2307"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gig",
            name="cal_feed_gig",
        ),
        migrations.RemoveField(
            model_name="historicalgig",
            name="cal_feed_gig",
        ),
        migrations.AddField(
            model_name="gig",
            name="cal_feed_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="historicalgig",
            name="cal_feed_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
