# Generated by Django 3.0 on 2020-02-23 01:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0005_abstractgig_schedule_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
