# Generated by Django 3.0.3 on 2020-02-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0005_abstractgig_schedule_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractgig',
            name='calltime',
        ),
        migrations.RemoveField(
            model_name='abstractgig',
            name='schedule_datetime',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='settime',
        ),
        migrations.AddField(
            model_name='gig',
            name='setdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractgig',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='gig',
            name='enddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
