# Generated by Django 3.0 on 2020-01-05 23:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0011_assoc_color'),
        ('gig', '0005_auto_20200105_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to='band.Band', null=True),
            preserve_default=False,
        ),
    ]
