# Generated by Django 3.0.3 on 2020-03-08 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gig", "0005_auto_20200308_0925"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalgig",
            name="cal_feed_id",
        ),
    ]
