# Generated by Django 3.0.3 on 2020-02-24 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0006_auto_20200222_2001'),
        ('gig', '0006_auto_20200222_1551'),
    ]

    operations = [
    ]
