# Generated by Django 3.0 on 2020-01-05 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0011_assoc_color'),
        ('gig', '0007_auto_20200105_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='band',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to='band.Band'),
            preserve_default=False,
        ),
    ]
