# Generated by Django 3.0 on 2020-01-11 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0011_assoc_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gig', '0009_gig_rss_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'No Plan'), (1, 'Definitely'), (2, 'Probably'), (3, "Don't Know"), (4, 'Probably Not'), (5, "Can't Do It"), (6, 'Not Interested')], default=0)),
                ('feedback_value', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('snooze_until', models.DateTimeField(null=True)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='gig.Gig')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL, verbose_name='member')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='band.Section', verbose_name='section')),
            ],
        ),
    ]
