# Generated by Django 3.0 on 2020-01-11 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0011_assoc_color'),
        ('gig', '0010_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='member',
        ),
        migrations.AddField(
            model_name='plan',
            name='assoc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='band.Assoc', verbose_name='assoc'),
            preserve_default=False,
        ),
    ]
