# Generated by Django 4.2.10 on 2024-02-26 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("band", "0013_alter_band_thumbnail_img"),
        ("gig", "0012_auto_20210604_1736"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gig",
            name="band",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                related_query_name="%(class)ss",
                to="band.band",
            ),
        ),
    ]
