# Generated by Django 3.0 on 2020-01-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0012_auto_20200111_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='feedback_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='snooze_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
