# Generated by Django 4.2.10 on 2024-03-09 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0013_alter_gig_band_alter_gig_status_and_more'),
        ('gig', '0013_gig_email_changes_historicalgig_email_changes_and_more'),
    ]

    operations = [
    ]
