# Generated by Django 4.2.10 on 2024-03-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0015_alter_historicalgig_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalgig',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical gig'},
        ),
        migrations.AddField(
            model_name='gig',
            name='leader_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalgig',
            name='leader_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgig',
            name='history_date',
            field=models.DateTimeField(),
        ),
    ]
