# Generated by Django 4.2.10 on 2024-03-16 15:33

from django.db import migrations

def textize_leader(apps, schema_editor):
    Gig = apps.get_model('gig', 'Gig')
    for g in Gig.objects.all():
        if g.leader:
            g.leader_text = g.leader.display_name
        g.save()

class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0016_alter_historicalgig_options_gig_leader_text_and_more'),
    ]

    operations = [
        migrations.RunPython(textize_leader)
    ]
