# Generated by Django 4.2.11 on 2024-03-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0018_alter_historicalgig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='has_call_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gig',
            name='has_end_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gig',
            name='has_set_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gig',
            name='is_full_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalgig',
            name='has_call_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalgig',
            name='has_end_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalgig',
            name='has_set_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalgig',
            name='is_full_day',
            field=models.BooleanField(default=False),
        ),
    ]
