# Generated by Django 4.2.16 on 2024-10-12 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0019_alter_gig_date_alter_gig_enddate_alter_gig_setdate_and_more'),
        ('gig', '0020_auto_20240325_1946'),
    ]

    operations = [
    ]
