# Generated by Django 4.2.15 on 2025-01-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0020_auto_20240325_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='safe_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='safe_enddate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='safe_setdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicalgig',
            name='safe_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicalgig',
            name='safe_enddate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicalgig',
            name='safe_setdate',
            field=models.DateTimeField(null=True),
        ),
    ]
