# Generated by Django 4.2.17 on 2025-02-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0020_auto_20240325_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='plans_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalgig',
            name='plans_locked',
            field=models.BooleanField(default=False),
        ),
    ]
