# Generated by Django 4.2.11 on 2024-03-25 23:46

# a data migration for moving from old, bad date/time handling to perfect, new date/time handling

from django.db import migrations
import pytz
import datetime

def save_dates(apps, schema_editor):

    Gig = apps.get_model('gig', 'Gig')
    for g in Gig.objects.all():

        # save away dates for safety
        g.safe_date = g.date
        g.safe_setdate = g.setdate
        g.safe_enddate = g.enddate

        g.save()

def unsave_dates(apps, schema_editor):
    Gig = apps.get_model('gig', 'Gig')
    for g in Gig.objects.all():

        # save away dates for safety
        g.date = g.safe_date
        g.setdate = g.safe_setdate
        g.enddate = g.safe_enddate

        g.save()


class Migration(migrations.Migration):


    dependencies = [
        ('gig', '0021_gig_safe_date_gig_safe_enddate_gig_safe_setdate_and_more'),
    ]

    operations = [
        migrations.RunPython(save_dates, unsave_dates)
    ]
