# Generated by Django 4.2.15 on 2024-11-08 15:53

from django.db import migrations
import go3.datetime_without_timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0022_save_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='date',
            field=go3.datetime_without_timezone.DateTimeWithoutTimezoneField(),
        ),
        migrations.AlterField(
            model_name='gig',
            name='enddate',
            field=go3.datetime_without_timezone.DateTimeWithoutTimezoneField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gig',
            name='setdate',
            field=go3.datetime_without_timezone.DateTimeWithoutTimezoneField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgig',
            name='date',
            field=go3.datetime_without_timezone.DateTimeWithoutTimezoneField(),
        ),
        migrations.AlterField(
            model_name='historicalgig',
            name='enddate',
            field=go3.datetime_without_timezone.DateTimeWithoutTimezoneField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgig',
            name='setdate',
            field=go3.datetime_without_timezone.DateTimeWithoutTimezoneField(blank=True, null=True),
        ),
    ]
