# Generated by Django 4.2.15 on 2025-01-05 16:42

from django.db import migrations
import pytz
from datetime import timedelta

def shift_dates(apps, schema_editor):

    def _shift(date, zone):
        if date:
            # since the date is zoneless, let's assume it's now UTC
            d = pytz.utc.localize(date)

            # shift it to the new zone
            d = d.astimezone(zone)
            return d
        return None

    Gig = apps.get_model('gig', 'Gig')
    for g in Gig.objects.all():

        # what band is this for
        b = g.band
        zone = pytz.timezone(b.timezone)

        g.date = _shift(g.date,zone)
        g.setdate = _shift(g.setdate,zone)
        g.enddate = _shift(g.enddate, zone)

        g.save()

def unshift_dates(apps, schema_editor):
    # put dates back the way they were
    def _unshift(date, zone):
        if date:
            # since the date is zoneless, let's assume it's now UTC
            d = zone.localize(date)

            # shift it to the new zone
            d = d.astimezone(pytz.utc)
            return d
        return None

    Gig = apps.get_model('gig', 'Gig')
    for g in Gig.objects.all():

        # what band is this for
        b = g.band
        zone = pytz.timezone(b.timezone)

        g.date = _unshift(g.date,zone)
        g.setdate = _unshift(g.setdate,zone)
        g.enddate = _unshift(g.enddate, zone)

        g.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0023_alter_gig_date_alter_gig_enddate_alter_gig_setdate_and_more'),
    ]

    operations = [
        migrations.RunPython(shift_dates, unshift_dates)
    ]
