# Generated by Django 4.2.17 on 2025-02-22 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0021_gig_plans_locked_historicalgig_plans_locked'),
        ('gig', '0024_change_dates_by_band_timezone'),
    ]

    operations = [
    ]
