# Generated by Django 4.2.15 on 2025-02-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0025_merge_20250222_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='gig',
            name='enddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gig',
            name='setdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgig',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalgig',
            name='enddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgig',
            name='setdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
