# Generated by Django 4.2.15 on 2025-02-26 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0026_alter_gig_date_alter_gig_enddate_alter_gig_setdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgig',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
