# Generated by Django 4.2.15 on 2025-03-02 00:05

from django.db import migrations
import pytz
import datetime

def restore_dates(apps, schema_editor):

    Gig = apps.get_model('gig', 'Gig')
    for g in Gig.objects.all():

        # save away dates for safety
        g.safe_date = g.date
        g.safe_setdate = g.setdate
        g.safe_enddate = g.enddate

        g.save()

def unrestore_dates(apps, schema_editor):
    """ do nothing, we should not have to undo this! """
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0027_alter_gig_date_alter_historicalgig_date'),
    ]


    operations = [
        migrations.RunPython(restore_dates, unrestore_dates)
    ]
