# Generated by Django 4.2.15 on 2025-03-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0029_gig_watchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='status_changed',
            field=models.BooleanField(default=False),
        ),
    ]
