# Generated by Django 4.2.22 on 2025-08-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0030_plan_status_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='public_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalgig',
            name='public_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
