# Generated by Django 4.2.22 on 2025-08-17 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0031_gig_public_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='rss_description',
        ),
        migrations.RemoveField(
            model_name='historicalgig',
            name='rss_description',
        ),
    ]
