# Generated by Django 4.2.27 on 2025-12-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0032_remove_gig_rss_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='rsvp_by_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalgig',
            name='rsvp_by_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
