# Generated by Django 4.2.28 on 2026-05-23 18:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gig', '0033_gig_rsvp_by_date_historicalgig_rsvp_by_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='safe_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gig',
            name='safe_enddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gig',
            name='safe_setdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gig',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watching', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalgig',
            name='safe_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgig',
            name='safe_enddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgig',
            name='safe_setdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
