# Generated by Django 6.0.7 on 2026-07-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0034_alter_gig_safe_date_alter_gig_safe_enddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='details_markdown',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalgig',
            name='details_markdown',
            field=models.BooleanField(default=True),
        ),
    ]
