# Generated by Django 6.0.7 on 2026-07-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0035_gig_details_markdown_historicalgig_details_markdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='details_markdown',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalgig',
            name='details_markdown',
            field=models.BooleanField(default=False),
        ),
    ]
