# Generated by Django 6.0.7 on 2026-07-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0036_alter_gig_details_markdown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='setlist_markdown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalgig',
            name='setlist_markdown',
            field=models.BooleanField(default=False),
        ),
    ]
