# Generated by Django 3.1.7 on 2021-03-14 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name="stat",
            name="name",
        ),
        migrations.AddField(
            model_name="stat",
            name="metric",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stats",
                to="stats.metric",
            ),
        ),
    ]
