# Generated by Django 3.1.7 on 2021-03-17 01:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0007_auto_20210314_1610"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stat",
            name="updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
