# Generated by Django 3.2.6 on 2021-08-14 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("band", "0013_alter_band_thumbnail_img"),
        ("stats", "0009_auto_20210316_2201"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bandmetric",
            name="band",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metrics",
                to="band.band",
            ),
        ),
    ]
