# Generated by Django 4.2.11 on 2024-06-01 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_alter_bandmetric_band'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='kind',
            field=models.IntegerField(choices=[(0, 'Daily'), (1, 'All Time'), (2, 'Daily Accumulate')], default=0),
        ),
        migrations.AlterField(
            model_name='stat',
            name='created',
            field=models.DateField(default=datetime.date(2024, 6, 1)),
        ),
    ]
