# Generated by Django 4.2.11 on 2024-06-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0012_alter_stat_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
