# Generated by Django 4.2.11 on 2024-06-01 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0013_alter_stat_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='stats.bandmetric'),
        ),
    ]
