# Generated by Django 4.2.11 on 2024-06-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0014_alter_stat_metric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='kind',
            field=models.IntegerField(choices=[(0, 'Daily'), (1, 'All Time'), (2, 'Daily Accumulate'), (3, 'Every')], default=0),
        ),
    ]
