# Generated by Django 3.0 on 2019-12-23 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hometown', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Assoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assocs', to='band.Band')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assocs', to=settings.AUTH_USER_MODEL, verbose_name='member')),
            ],
        ),
    ]
