# Generated by Django 3.0 on 2020-01-15 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('band', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assoc',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assocs', to=settings.AUTH_USER_MODEL, verbose_name='member'),
        ),
    ]
