# Generated by Django 3.0 on 2019-12-18 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('band', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assoc',
            name='member',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assocs', to='member.Member', verbose_name='member'),
            preserve_default=False,
        ),
    ]
