# Generated by Django 3.0 on 2019-12-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0002_auto_20191227_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='anyone_can_create_gigs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='band',
            name='anyone_can_manage_gigs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='band',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='band',
            name='images',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='band',
            name='member_links',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='band',
            name='new_member_message',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='band',
            name='plan_feedback',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='band',
            name='rss_feed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='band',
            name='send_updates_by_default',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='band',
            name='share_gigs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='band',
            name='simple_planning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='band',
            name='thumbnail_img',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='band',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='condensed_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='hometown',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='shortname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
