# Generated by Django 3.0 on 2019-12-18 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0002_assoc_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='hometown',
            field=models.CharField(default='Boston', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assoc',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assocs', to='band.Band'),
        ),
    ]
