# Generated by Django 3.0 on 2020-01-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0002_assoc_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
