# Generated by Django 3.0 on 2019-12-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0003_auto_20191227_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='assoc',
            name='email_me',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assoc',
            name='hide_from_schedule',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assoc',
            name='is_band_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assoc',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assoc',
            name='is_invited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assoc',
            name='is_multisectional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assoc',
            name='is_occasional',
            field=models.BooleanField(default=False),
        ),
    ]
