# Generated by Django 3.0 on 2019-12-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0004_auto_20191227_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='timezone',
            field=models.CharField(default='UTC', max_length=200),
        ),
    ]
