# Generated by Django 3.0 on 2020-01-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0004_auto_20200119_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
