# Generated by Django 3.0 on 2020-01-22 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0006_auto_20200120_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assoc',
            name='default_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='default_assocs', to='band.Section'),
        ),
    ]
