# Generated by Django 3.0 on 2020-02-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0007_auto_20200121_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Dormant'), (2, 'Deleted')], default=0),
        ),
    ]
