# Generated by Django 3.0 on 2019-12-30 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0008_auto_20191230_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='assoc',
            name='default_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_section', to='band.Section'),
        ),
    ]
