# Generated by Django 3.0 on 2019-12-31 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0009_assoc_default_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assoc',
            name='default_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_section', to='band.Section'),
        ),
    ]
