# Generated by Django 3.1.7 on 2021-03-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("band", "0009_auto_20210313_1431"),
    ]

    operations = [
        migrations.AddField(
            model_name="assoc",
            name="join_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
