# Generated by Django 3.1.7 on 2021-03-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("band", "0010_assoc_join_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assoc",
            name="join_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
