# Generated by Django 3.0 on 2020-01-03 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0010_auto_20191231_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='assoc',
            name='color',
            field=models.IntegerField(default=0),
        ),
    ]
