# Generated by Django 3.0 on 2020-01-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0011_assoc_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assoc',
            name='is_band_admin',
        ),
        migrations.RemoveField(
            model_name='assoc',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='assoc',
            name='is_invited',
        ),
        migrations.AddField(
            model_name='assoc',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not Confirmed'), (1, 'Confirmed'), (2, 'Occasional'), (3, 'Invited'), (4, 'Alumni'), (5, 'Admin')], default=0),
        ),
    ]
