# Generated by Django 4.2.10 on 2024-03-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0013_alter_band_thumbnail_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='default_language',
            field=models.CharField(choices=[('de', 'German'), ('en-US', 'English (US)'), ('en-GB', 'English (UK, AU, NZ, ...)'), ('fr', 'French'), ('it', 'Italian')], default='en-US', max_length=200),
        ),
    ]
