# Generated by Django 4.2.10 on 2024-03-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0015_alter_band_timezone'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('band_id', 'order'), name='band_section_unique'),
        ),
    ]
