# Generated by Django 4.2.10 on 2024-03-18 00:32

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0016_section_band_section_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='section',
            name='band_section_unique',
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('band_id', 'order'), name='band_section_unique'),
        ),
    ]
