# Generated by Django 4.2.11 on 2024-03-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0017_remove_section_band_section_unique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.IntegerField(default=None),
        ),
    ]
