# Generated by Django 4.2.11 on 2024-03-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0018_alter_section_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
