# Generated by Django 4.2.11 on 2024-03-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0019_alter_band_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='images',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='member_links',
            field=models.TextField(blank=True, null=True),
        ),
    ]
