# Generated by Django 4.2.11 on 2024-03-23 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0019_assoc_is_alum'),
        ('band', '0020_alter_band_images_alter_band_member_links'),
    ]

    operations = [
    ]
