# Generated by Django 4.2.11 on 2024-03-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0021_merge_20240323_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assoc',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not Confirmed'), (1, 'Confirmed'), (2, 'Invited'), (3, 'Deprecated Alumni'), (4, 'Pending')], default=0),
        ),
    ]
