# Generated by Django 4.2.11 on 2024-03-23 16:14

from django.db import migrations
from band.util import AssocStatusChoices

def migrate_alums(apps, schema_editor):
    """
    - Any assoc with status of "CONFIRMED" or "ALUMNI" should have the is_alum flag set
    - Any assoc with status of "ALUMNI" should be set to "NOT_CONFIRMED"
    """
    Assoc = apps.get_model('band','Assoc')
    for a in Assoc.objects.all():
        if a.status == AssocStatusChoices.CONFIRMED:
            a.is_alum = True
            a.save()
        elif a.status == AssocStatusChoices.deprecated_alumni:
            a.is_alum = True
            a.status = AssocStatusChoices.NOT_CONFIRMED
            a.save()

def unmigrate_alums(apps, schema_editor):
    """
    Don't do anything - this is just here for testing
    """
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('band', '0022_alter_assoc_status'),
    ]

    operations = [
        migrations.RunPython(migrate_alums, unmigrate_alums)
    ]
