# Generated by Django 4.2.11 on 2024-06-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0023_auto_20240323_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='default_language',
            field=models.CharField(choices=[('de', 'German'), ('en-US', 'English (US)'), ('en-GB', 'English (UK, AU, NZ, ...)'), ('es', 'Spanish'), ('fr', 'French'), ('it', 'Italian')], default='en-US', max_length=200),
        ),
    ]
