# Generated by Django 4.2.17 on 2025-02-27 07:28

import uuid
from django.db import migrations, models

def add_api_key(apps, schema_editor):
    Band = apps.get_model('band', 'Band')
    for band in Band.objects.all():
        band.api_key = uuid.uuid4()
        band.save()

def remove_api_key(apps, schema_editor):
    Band = apps.get_model('band', 'Band')
    for band in Band.objects.all():
        band.api_key = None
        band.save()

class Migration(migrations.Migration):

    dependencies = [
        ('band', '0025_alter_band_default_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='api_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RunPython(add_api_key, remove_api_key),
    ]
