# Generated by Django 4.2.15 on 2025-03-18 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0025_alter_band_default_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='band',
            options={'ordering': ['name']},
        ),
    ]
