# Generated by Django 4.2.22 on 2025-08-17 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0026_alter_band_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='rss_feed',
        ),
    ]
