# Generated by Django 4.2.28 on 2026-05-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0027_remove_band_rss_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='invite_occasionals_by_default',
            field=models.BooleanField(default=True),
        ),
    ]
