# Generated by Django 3.0 on 2019-12-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='seen_motd_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
