# Generated by Django 3.0 on 2020-01-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberpreferences',
            name='default_view',
            field=models.IntegerField(choices=[(0, 'Agenda'), (1, 'Grid'), (2, 'Calendar')], default=0),
        ),
    ]
