# Generated by Django 3.0 on 2019-12-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20191223_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberpreferences',
            name='locale',
            field=models.CharField(default='en', max_length=200),
        ),
    ]
