# Generated by Django 3.0 on 2019-12-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20191223_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='statement',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
