# Generated by Django 3.0.3 on 2020-02-12 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberpreferences',
            old_name='locale',
            new_name='language',
        ),
    ]
