# Generated by Django 3.0.7 on 2020-06-09 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0004_auto_20200402_0143"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memberpreferences",
            name="show_long_agenda",
        ),
    ]
