# Generated by Django 3.0.3 on 2020-02-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20200211_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberpreferences',
            name='language',
            field=models.CharField(choices=[('de', 'German'), ('en-us', 'English (US)'), ('en-uk', 'English (UK)'), ('fr', 'French'), ('it', 'Italian')], default='en', max_length=200),
        ),
    ]
