# Generated by Django 3.0 on 2020-01-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_remove_memberpreferences_email_new_gig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='seen_motd_time',
        ),
        migrations.AddField(
            model_name='member',
            name='motd_dirty',
            field=models.BooleanField(default=True),
        ),
    ]
