# Generated by Django 3.0 on 2020-01-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20200105_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='show_long_agenda',
        ),
        migrations.AddField(
            model_name='memberpreferences',
            name='show_long_agenda',
            field=models.BooleanField(default=True),
        ),
    ]
