# Generated by Django 3.1.8 on 2021-04-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0008_emailconfirmation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailconfirmation",
            name="language",
            field=models.CharField(
                choices=[
                    ("de", "German"),
                    ("en-US", "English (US)"),
                    ("en-GB", "English (UK)"),
                    ("fr", "French"),
                    ("it", "Italian"),
                ],
                default="en",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="invite",
            name="language",
            field=models.CharField(
                choices=[
                    ("de", "German"),
                    ("en-US", "English (US)"),
                    ("en-GB", "English (UK)"),
                    ("fr", "French"),
                    ("it", "Italian"),
                ],
                default="en",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="memberpreferences",
            name="language",
            field=models.CharField(
                choices=[
                    ("de", "German"),
                    ("en-US", "English (US)"),
                    ("en-GB", "English (UK)"),
                    ("fr", "French"),
                    ("it", "Italian"),
                ],
                default="en",
                max_length=200,
            ),
        ),
    ]
