# Generated by Django 4.2.10 on 2024-03-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_alter_emailconfirmation_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='go2_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
