# Generated by Django 4.2.11 on 2024-07-13 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0019_member_is_beta_tester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_beta_tester',
        ),
    ]
