# Generated by Django 4.2.11 on 2024-06-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0019_member_is_beta_tester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberpreferences',
            name='agenda_layout',
            field=models.IntegerField(choices=[(0, 'Weigh In'), (1, 'By Band'), (2, 'Single List')], default=0, verbose_name='Schedule page layout'),
        ),
    ]
