# Generated by Django 4.2.11 on 2024-07-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0019_member_is_beta_tester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberpreferences',
            name='notify_on_gig_responses',
            field=models.BooleanField(default=False, verbose_name='Notify me when members rsvp to gigs'),
        ),
    ]
