# Generated by Django 4.2.11 on 2024-07-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0021_memberpreferences_agenda_band'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberpreferences',
            name='agenda_layout',
            field=models.IntegerField(choices=[(0, 'Weigh In'), (1, 'By Band'), (2, 'Single List')], default=2, verbose_name='Schedule page layout'),
        ),
    ]
