# Generated by Django 4.2.11 on 2024-07-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0023_memberpreferences_agenda_use_classic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberpreferences',
            name='agenda_use_classic',
            field=models.BooleanField(default=False, verbose_name='Use old schedule page layout'),
        ),
    ]
