# Generated by Django 4.2.14 on 2024-09-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0024_alter_memberpreferences_agenda_use_classic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='language',
            field=models.CharField(choices=[('de', 'Deutsch'), ('en-US', 'English (US)'), ('en-GB', 'English (UK, AU, NZ, ...)'), ('es', 'Español'), ('fr', 'Français'), ('it', 'Italiano')], default='en-US', max_length=200),
        ),
        migrations.AlterField(
            model_name='invite',
            name='language',
            field=models.CharField(choices=[('de', 'Deutsch'), ('en-US', 'English (US)'), ('en-GB', 'English (UK, AU, NZ, ...)'), ('es', 'Español'), ('fr', 'Français'), ('it', 'Italiano')], default='en-US', max_length=200),
        ),
        migrations.AlterField(
            model_name='memberpreferences',
            name='language',
            field=models.CharField(choices=[('de', 'Deutsch'), ('en-US', 'English (US)'), ('en-GB', 'English (UK, AU, NZ, ...)'), ('es', 'Español'), ('fr', 'Français'), ('it', 'Italiano')], default='en-US', max_length=200, verbose_name='Language'),
        ),
    ]
