# Generated by Django 4.2.17 on 2025-02-27 16:52

import uuid
from django.db import migrations, models, transaction


def add_api_key(apps, schema_editor):
    Member = apps.get_model('member', 'Member')
    with transaction.atomic():
        update_list = []
        for member in Member.objects.filter(api_key__isnull=True):
            member.api_key = str(uuid.uuid4())
            update_list.append(member)
        Member.objects.bulk_update(update_list, ['api_key'])

def remove_api_key(apps, schema_editor):
    Member = apps.get_model('member', 'Member')
    with transaction.atomic():
        Member.objects.update(api_key=None)


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0027_memberpreferences_auto_update_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='api_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RunPython(add_api_key, remove_api_key),
    ]
