# Generated by Django 4.2.17 on 2025-03-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0027_memberpreferences_auto_update_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='api_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
