# Generated by Django 4.2.17 on 2025-03-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0030_member_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberpreferences',
            name='agenda_show_location',
            field=models.BooleanField(default=False),
        ),
    ]
