# Generated by Django 4.2.15 on 2025-03-23 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0026_alter_band_options'),
        ('member', '0031_memberpreferences_agenda_show_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberpreferences',
            name='agenda_band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='band.band'),
        ),
    ]
