# Generated by Django 4.2.30 on 2026-09-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0033_alter_memberpreferences_current_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberpreferences',
            name='agenda_hide_declined',
            field=models.BooleanField(default=False),
        ),
    ]
