# Generated by Django 4.2.30 on 2026-09-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0033_alter_memberpreferences_current_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberpreferences',
            name='agenda_layout',
            field=models.IntegerField(choices=[(0, 'Weigh In'), (1, 'By Band'), (2, 'Single List'), (3, 'Has Response'), (4, 'Not Canceled or Declined')], default=2, verbose_name='Schedule page layout'),
        ),
    ]
