name: Build and Publish Image to GCR

on:
  workflow_call:
    inputs:
      push_to_gcr:
        type: boolean
        description: Push image to Google Container Registry
        default: "${{ github.event_name != 'pull_request' }}"
    outputs:
      image_name:
        value: ${{ jobs.build_and_publish_image.outputs.image_name }}
        description: "Name of the image that was built and pushed to Google's Container Registry"
      short_sha_tag:
        value: ${{ jobs.build_and_publish_image.outputs.short_sha_tag }}
        description: "short_sha_tag"
  workflow_dispatch:
    inputs:
      push_to_gcr:
        type: boolean
        description: Push image to Google Container Registry
        default: false

jobs:
  build_and_publish_image:
    name: "Build and Publish Images"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      image_name: ${{ fromJSON(steps.publish.outputs.metadata)['image.name'] }}
      short_sha_tag: ${{ steps.record_summary.outputs.short_sha_tag }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        if: inputs.push_to_gcr
        uses: google-github-actions/auth@v2
        id: auth
        with:
          workload_identity_provider: "${{ vars.WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "${{ vars.GHA_SERVICE_ACCOUNT_EMAIL }}"
          token_format: access_token
          access_token_scopes: "https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/devstorage.read_write"

      - name: Set up Docker Buildx
        id: buildx

        uses: docker/setup-buildx-action@v3
      - name: Login to GCR
        if: inputs.push_to_gcr
        uses: docker/login-action@v3
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Generate Docker Tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            "${{ vars.CONTAINER_IMAGE_REPO }}/website"
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,value=latest,enable=${{ inputs.push_to_gcr }}

      - name: Build and Push to GCR
        id: publish
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: ${{ inputs.push_to_gcr }}
          tags: ${{ steps.meta.outputs.tags }}
          # Using native GitHub action caching as shown here:
          # https://github.com/docker/build-push-action/issues/252#issuecomment-889339470
          cache-from: type=gha,scope=$${{ github.workflow }}
          cache-to: type=gha,scope=$${{ github.workflow }},mode=max

      - name: Record Step Summary
        id: record_summary
        env:
          image_details: "${{ steps.publish.outputs.metadata }}"
          image_id: "${{ steps.publish.outputs.imageid }}"
          image_name: "${{ fromJSON(steps.publish.outputs.metadata)['image.name'] }}"
          metadata: "${{ steps.meta.outputs.json }}"
        run: |
          echo "short_sha_tag=$(git rev-parse --short HEAD)" | tee -a $GITHUB_OUTPUT
          cat << SUMMARY | tee --append "$GITHUB_STEP_SUMMARY"
          ## Image Build - murga-o-matic-website

          - **ID / Digest**:

            \`$image_id\`
          - **Image Name**:

            \`$image_name\`

          ### Details

          <details>
          <summary>Expand Metadata</summary>

          \`\`\`json
          $(jq -r '.' <<<"$metadata")
          \`\`\`
          </details>

          <details>
          <summary>Expand Image Details</summary>

          \`\`\`json
          $(jq -r '.' <<<"$image_details")
          \`\`\`
          </details>
          SUMMARY
